### ISSUE TITLE
Usage examples from a bib file

### ISSUE THREAD

**Issue by k4rtik** [andrewcmyers/bibweb#4]
Hi Andrew

Seeing your announcement of this tool on Twitter, I was trying it out this morning on the [Quantum PL & Verification bibliography](https://git.io/qpl-bib) that I maintain, see: https://github.com/QuantumPL/bib/blob/main/bbt.bib

Is there a way to pass a bib file directly to this tool? If not, how much work needs to be done to write a script that just takes a bib file and produces some HTML output?

**Comment by andrewcmyers** [comment]
Take a look at the .bibweb examples as a starting point.

**Comment by k4rtik** [comment]
Thanks, I tried that after replacing the `bibfile` parameter to my bib file:
```
❯ ./bibweb complex-example.bibweb
Found 179 objects in BibTeX file.
Found 2 publications in script.
Creating output file pubs.html
Creating output file pubs-topic.html
Bad year in publication abadi99
Warning: year bound to null
Creating output file recent-pubs.html
```

It doesn't pick any pubs from my bib file. I also tried the simpler `example.bibweb` similarly.

What I am trying to understand is do I need to manually write a structure as follows?
```
pubs {
    abadi99 {
      authors: Mart&iacute;n Abadi and Andrew D. Gordon
      topic: Security languages
      project: spi
      blurb {
        A seminal paper on using programming languages to model cryptographic
        protocols.
      }
    }
    dummy1 {
        pubtype: inproceedings
        title: A fake paper
        authors: John Doe and Jane Doe
        topic: security
        booktitle: A fake conference
        year: 2015
        month: June
    }
}
```
or can that be generated from the bibfile somehow?

**Comment by andrewcmyers** [comment]
Yes, this is how you tell it which publications to include. You don't have to provide any extra information in the way that this example does, however.

**Comment by k4rtik** [comment]
So how do I get the tool to pick up the ~140 publications from the bib file?

**Comment by andrewcmyers** [comment]
I updated it so it automatically imports all publications if you don't specify a pubs block. See if this works better for you.

**Comment by k4rtik** [comment]
Thanks, so much! It's working now!

There are some minor bibtex issues such as:
- `don't know how to expand parameterless macro `
- `HTML conversion failed on Beno{\^i}t Valiron : Unexpected char after backslash: ^`
- `(Unhandled publication type incollection)`
- `(Unhandled publication type book)`

but nothing that I can't easily fix myself.

**Comment by andrewcmyers** [comment]
For what it's worth, I've fixed some of the problems you identified and made it easier to import from a .bib file.

**Comment by k4rtik** [comment]
Thanks, it's looking better!
